export const stmBusData = {
  "Réseau de Jour": [
    { id: "10", name: "De Lorimier", dir: ["Sud", "Nord"] },
    { id: "11", name: "Parc-du-Mont-Royal / Ridgewood", dir: ["Ouest", "Est"] },
    { id: "12", name: "Île-des-Soeurs", dir: ["Sud", "Nord"] },
    { id: "13", name: "Christophe-Colomb", dir: ["Sud", "Nord"] },
    { id: "14", name: "Atateken", dir: ["Sud", "Nord"] },
    { id: "16", name: "Graham", dir: ["Est", "Ouest"] },
    { id: "17", name: "Décarie", dir: ["Sud", "Nord"] },
    { id: "18", name: "Beaubien", dir: ["Est", "Ouest"] },
    { id: "19", name: "Chabanel / Marché Central", dir: ["Est", "Ouest"] },
    { id: "20", name: "Crémazie / Marché Central", dir: ["Est", "Ouest"] },
    { id: "22", name: "Notre-Dame", dir: ["Est", "Ouest"] },
    { id: "24", name: "Sherbrooke", dir: ["Ouest", "Est"] },
    { id: "25", name: "Angus", dir: ["Nord", "Sud"] },
    { id: "26", name: "Mercier-Est", dir: ["Est", "Ouest"] },
    { id: "27", name: "Boulevard Saint-Joseph", dir: ["Ouest", "Est"] },
    { id: "28", name: "Honoré-Beaugrand", dir: ["Sud", "Nord"] },
    { id: "29", name: "Rachel", dir: ["Est", "Ouest"] },
    { id: "30", name: "Saint-Denis / Saint-Hubert", dir: ["Sud", "Nord"] },
    { id: "31", name: "Saint-Denis", dir: ["Sud", "Nord"] },
    { id: "32", name: "Lacordaire", dir: ["Sud", "Nord"] },
    { id: "33", name: "Langelier", dir: ["Sud", "Nord"] },
    { id: "34", name: "Sainte-Catherine", dir: ["Est", "Ouest"] },
    { id: "35", name: "Griffintown", dir: ["Est", "Ouest"] },
    { id: "36", name: "Monk", dir: ["Est", "Ouest"] },
    { id: "37", name: "Jolicoeur", dir: ["Ouest", "Est"] },
    { id: "38", name: "De l'Église", dir: ["Nord", "Sud"] },
    { id: "39", name: "Des Grandes-Prairies", dir: ["Est", "Ouest"] },
    { id: "40", name: "Henri-Bourassa-Est", dir: ["Est", "Ouest"] },
    { id: "41", name: "Saint-Michel / Ahuntsic", dir: ["Est", "Ouest"] },
    { id: "43", name: "Monselet", dir: ["Est", "Ouest"] },
    { id: "44", name: "Armand-Bombardier", dir: ["Sud", "Nord"] },
    { id: "45", name: "Papineau", dir: ["Sud", "Nord"] },
    { id: "46", name: "Casgrain", dir: ["Est", "Ouest"] },
    { id: "47", name: "Masson", dir: ["Est", "Ouest"] },
    { id: "48", name: "Perras", dir: ["Est", "Ouest"] },
    { id: "49", name: "Maurice-Duplessis", dir: ["Est", "Ouest"] },
    { id: "50", name: "Vieux-Montréal / Vieux-Port", dir: ["Est", "Ouest"] },
    { id: "51", name: "Édouard-Montpetit", dir: ["Est", "Ouest"] },
    { id: "52", name: "de Liège", dir: ["Ouest", "Est"] },
    { id: "54", name: "Charland / Chabanel", dir: ["Est", "Ouest"] },
    { id: "55", name: "Boulevard Saint-Laurent", dir: ["Sud", "Nord"] },
    { id: "56", name: "Saint-Hubert", dir: ["Sud", "Nord"] },
    { id: "57", name: "Charlevoix", dir: ["Sud", "Nord"] },
    { id: "61", name: "Wellington", dir: ["Est", "Ouest"] },
    { id: "63", name: "Girouard", dir: ["Sud", "Nord"] },
    { id: "64", name: "Grenet", dir: ["Sud", "Nord"] },
    { id: "66", name: "The Boulevard", dir: ["Sud", "Nord"] },
    { id: "67", name: "Saint-Michel", dir: ["Nord", "Sud"] },
    { id: "68", name: "Pierrefonds", dir: ["Est", "Ouest"] },
    { id: "69", name: "Gouin", dir: ["Est", "Ouest"] },
    { id: "70", name: "Bois-Franc", dir: ["Est", "Ouest"] },
    { id: "71", name: "Pointe-Saint-Charles", dir: ["Sud", "Nord"] },
    { id: "72", name: "Alfred-Nobel", dir: ["Est", "Ouest"] },
    { id: "73", name: "Dalton", dir: ["Est", "Ouest"] },
    { id: "74", name: "Bridge", dir: ["Nord", "Sud"] },
    { id: "79", name: "Gouin", dir: ["Est", "Ouest"] },
    { id: "80", name: "Avenue du Parc", dir: ["Sud", "Nord"] },
    { id: "81", name: "Saint-Jean-Baptiste", dir: ["Nord", "Sud"] },
    { id: "85", name: "Hochelaga", dir: ["Est", "Ouest"] },
    { id: "86", name: "Pointe-aux-Trembles", dir: ["Est", "Ouest"] },
    { id: "90", name: "Saint-Jacques", dir: ["Est", "Ouest"] },
    { id: "92", name: "Jean-Talon Ouest", dir: ["Est", "Ouest"] },
    { id: "93", name: "Jean-Talon", dir: ["Est", "Ouest"] },
    { id: "94", name: "D'Iberville", dir: ["Sud", "Nord"] },
    { id: "95", name: "Bélanger", dir: ["Est", "Ouest"] },
    { id: "97", name: "Avenue-du-Mont-Royal", dir: ["Est", "Ouest"] },
    { id: "99", name: "Villeray", dir: ["Est", "Ouest"] },
    { id: "100", name: "Crémazie", dir: ["Est", "Ouest"] },
    { id: "101", name: "Saint-Patrick", dir: ["Est", "Ouest"] },
    { id: "102", name: "Somerled", dir: ["Est", "Ouest"] },
    { id: "103", name: "Monkland", dir: ["Est", "Ouest"] },
    { id: "104", name: "Cavendish", dir: ["Est", "Ouest"] },
    { id: "105", name: "Sherbrooke", dir: ["Est", "Ouest"] },
    { id: "106", name: "Newman", dir: ["Est", "Ouest"] },
    { id: "107", name: "Verdun", dir: ["Ouest", "Est"] },
    { id: "108", name: "Bannantyne", dir: ["Est", "Ouest"] },
    { id: "110", name: "Centrale", dir: ["Est", "Ouest"] },
    { id: "112", name: "Airlie", dir: ["Est", "Ouest"] },
    { id: "113", name: "Lapierre", dir: ["Est", "Ouest"] },
    { id: "114", name: "Angrignon", dir: ["Sud", "Nord"] },
    { id: "115", name: "Paré", dir: ["Est", "Ouest"] },
    { id: "117", name: "O'Brien", dir: ["Sud", "Nord"] },
    { id: "119", name: "Rockland", dir: ["Nord", "Sud"] },
    { id: "120", name: "Royalmount", dir: ["Nord", "Sud"] },
    { id: "121", name: "Sauvé / Côte-Vertu", dir: ["Est", "Ouest"] },
    { id: "123", name: "Dollard / Shevchenko", dir: ["Sud", "Nord"] },
    { id: "124", name: "Victoria", dir: ["Sud", "Nord"] },
    { id: "125", name: "Ontario", dir: ["Est", "Ouest"] },
    { id: "126", name: "Thimens / Grenet", dir: ["Est", "Ouest"] },
    { id: "127", name: "Alexis-Nihon", dir: ["Nord", "Sud"] },
    { id: "128", name: "Saint-Laurent", dir: ["Sud", "Nord"] },
    { id: "129", name: "Côte-Sainte-Catherine", dir: ["Nord", "Sud"] },
    { id: "131", name: "De l'Assomption", dir: ["Sud", "Nord"] },
    { id: "135", name: "De l'Esplanade", dir: ["Sud", "Nord"] },
    { id: "136", name: "Viau", dir: ["Sud", "Nord"] },
    { id: "138", name: "Notre-Dame-de-Grâce", dir: ["Est", "Ouest"] },
    { id: "139", name: "Pie-IX", dir: ["Sud", "Nord"] },
    { id: "140", name: "Fleury", dir: ["Ouest", "Est"] },
    { id: "141", name: "Jean-Talon Est", dir: ["Est", "Ouest"] },
    { id: "144", name: "Avenue des Pins", dir: ["Est", "Ouest"] },
    { id: "146", name: "Christophe-Colomb / Meilleur", dir: ["Est", "Ouest"] },
    { id: "150", name: "René-Lévesque", dir: ["Est", "Ouest"] },
    { id: "155", name: "Wilderton", dir: ["Nord", "Sud"] },
    { id: "160", name: "Barclay", dir: ["Est", "Ouest"] },
    { id: "161", name: "Van Horne", dir: ["Est", "Ouest"] },
    { id: "162", name: "Westminster", dir: ["Est", "Ouest"] },
    { id: "164", name: "Dudemaine", dir: ["Est", "Ouest"] },
    { id: "165", name: "Côte-des-Neiges", dir: ["Sud", "Nord"] },
    { id: "166", name: "Queen-Mary", dir: ["Sud", "Nord"] },
    { id: "168", name: "Cité-du-Havre", dir: ["Sud", "Nord"] },
    { id: "170", name: "Keller", dir: ["Sud", "Nord"] },
    { id: "171", name: "Henri-Bourassa", dir: ["Est", "Ouest"] },
    { id: "172", name: "Du Golf", dir: ["Sud", "Nord"] },
    { id: "174", name: "Côte-Vertu", dir: ["Est", "Ouest"] },
    { id: "175", name: "Griffith / Saint-François", dir: ["Est", "Ouest"] },
    { id: "176", name: "Berlioz", dir: ["Sud", "Nord"] },
    { id: "177", name: "Thimens", dir: ["Est", "Ouest"] },
    { id: "179", name: "De l'Acadie", dir: ["Sud", "Nord"] },
    { id: "180", name: "De Salaberry", dir: ["Est", "Ouest"] },
    { id: "183", name: "Gouin Est", dir: ["Est", "Ouest"] },
    { id: "185", name: "Sherbrooke", dir: ["Est", "Ouest"] },
    { id: "186", name: "Sherbrooke-Est", dir: ["Est", "Ouest"] },
    { id: "187", name: "René-Lévesque", dir: ["Est", "Ouest"] },
    { id: "188", name: "Couture", dir: ["Est", "Ouest"] },
    { id: "189", name: "Notre-Dame", dir: ["Est", "Ouest"] },
    { id: "190", name: "Norman", dir: ["Est", "Ouest"] },
    { id: "192", name: "Robert", dir: ["Est", "Ouest"] },
    { id: "193", name: "Jarry", dir: ["Est", "Ouest"] }
  ],

  "Réseau Express": [
    { id: "401", name: "Express Saint-Charles", dir: ["Sud", "Nord"] },
    { id: "405", name: "Express Bord-du-Lac", dir: ["Est", "Ouest"] },
    { id: "407", name: "Express Île-Bizard", dir: ["Est", "Ouest"] },
    { id: "409", name: "Express Des Sources", dir: ["Sud", "Nord"] },
    { id: "410", name: "Express Notre-Dame", dir: ["Est", "Ouest"] },
    { id: "411", name: "Express Lionel-Groulx", dir: ["Est", "Ouest"] },
    { id: "419", name: "Express John Abbott", dir: ["Est", "Ouest"] },
    { id: "420", name: "Express Notre-Dame-de-Grâce", dir: ["Ouest", "Est"] },
    { id: "425", name: "Express Anse-à-l'Orme", dir: ["Est", "Ouest"] },
    { id: "427", name: "Express Saint-Joseph", dir: ["Ouest", "Est"] },
    { id: "428", name: "Express Parcs industriels de l'Est", dir: ["Sud", "Nord"] },
    { id: "430", name: "Express Pointe-aux-Trembles", dir: ["Est", "Ouest"] },
    { id: "432", name: "Express Lacordaire", dir: ["Sud", "Nord"] },
    { id: "439", name: "Express Pie-IX", dir: ["Sud", "Nord"] },
    { id: "440", name: "Express Charleroi", dir: ["Est", "Ouest"] },
    { id: "444", name: "Express Cégep Marie-Victorin", dir: ["Nord", "Sud"] },
    { id: "445", name: "Express Papineau", dir: ["Ouest", "Est"] },
    { id: "448", name: "Express Maurice-Duplessis", dir: ["Ouest", "Est"] },
    { id: "449", name: "Express Rivière-des-Prairies", dir: ["Sud", "Nord"] },
    { id: "460", name: "Express Métropolitaine", dir: ["Est", "Ouest"] },
    { id: "465", name: "Express Côte-des-Neiges", dir: ["Nord", "Sud"] },
    { id: "467", name: "Express Saint-Michel", dir: ["Sud", "Nord"] },
    { id: "468", name: "Express Pierrefonds / Gouin", dir: ["Est", "Ouest"] },
    { id: "469", name: "Express Henri-Bourassa", dir: ["Est", "Ouest"] },
    { id: "470", name: "Express Pierrefonds", dir: ["Est", "Ouest"] },
    { id: "475", name: "Express Dollard-des-Ormeaux", dir: ["Est", "Ouest"] },
    { id: "480", name: "Express du Parc", dir: ["Sud", "Nord"] },
    { id: "485", name: "Express Antoine-Faucon", dir: ["Est", "Ouest"] },
    { id: "486", name: "Express Sherbrooke", dir: ["Est", "Ouest"] },
    { id: "487", name: "Express Bout-de-l'Île", dir: ["Est", "Ouest"] },
    { id: "491", name: "Express Provost", dir: ["Est", "Ouest"] },
    { id: "496", name: "Express Victoria", dir: ["Est", "Ouest"] },
    { id: "747", name: "YUL Aéroport / Centre-Ville", dir: ["Vers Centre-ville", "Vers Aéroport"] }
  ],

    "Réseau de Nuit": [
    { id: "350", name: "Verdun / LaSalle", dir: ["Est", "Ouest"] },
    { id: "353", name: "Lacordaire / Maurice-Duplessis", dir: ["Est", "Ouest"] },
    { id: "354", name: "Sainte-Anne-de-Bellevue / Centre-ville", dir: ["Est", "Ouest"] },
    { id: "355", name: "Pie-IX", dir: ["Sud", "Nord"] },
    { id: "356", name: "Lachine / YUL Aéroport / Des Sources", dir: ["Est", "Ouest"] },
    { id: "357", name: "Saint-Michel", dir: ["Sud", "Nord"] },
    { id: "358", name: "René-Lévesque", dir: ["Est", "Ouest"] },
    { id: "359", name: "Papineau", dir: ["Sud", "Nord"] },
    { id: "360", name: "Avenue des Pins", dir: ["Est", "Ouest"] },
    { id: "361", name: "Saint-Denis", dir: ["Sud", "Nord"] },
    { id: "362", name: "Hochelaga / Notre-Dame", dir: ["Ouest", "Est"] },
    { id: "363", name: "Boulevard Saint-Laurent", dir: ["Sud", "Nord"] },
    { id: "364", name: "Sherbrooke / Joseph-Renaud", dir: ["Est", "Ouest"] },
    { id: "365", name: "Avenue du Parc", dir: ["Sud", "Nord"] },
    { id: "368", name: "Avenue-du-Mont-Royal", dir: ["Est", "Ouest"] },
    { id: "369", name: "Côte-des-Neiges", dir: ["Sud", "Nord"] },
    { id: "370", name: "Rosemont", dir: ["Est", "Ouest"] },
    { id: "371", name: "Décarie", dir: ["Sud", "Nord"] },
    { id: "372", name: "Jean-Talon", dir: ["Est", "Ouest"] },
    { id: "376", name: "Pierrefonds / Centre-ville", dir: ["Est", "Ouest"] },
    { id: "378", name: "Sauvé / YUL Aéroport", dir: ["Est", "Ouest"] },
    { id: "380", name: "Henri-Bourassa", dir: ["Est", "Ouest"] },
    { id: "382", name: "Pierrefonds / Saint-Charles", dir: ["Est", "Ouest"] }
  ],

  "Navettes Or & Spéciales": [
    { id: "252", name: "Navette Or Montréal-Nord", dir: ["Ouest", "Est"] },
    { id: "253", name: "Navette Or Saint-Michel", dir: ["Nord", "Sud"] },
    { id: "254", name: "Navette Or Rosemont", dir: ["Est", "Ouest"] },
    { id: "256", name: "Navette Or LaSalle", dir: ["Est", "Ouest"] },
    { id: "257", name: "Navette Or Rivière-des-Prairies", dir: ["Est", "Ouest"] },
    { id: "258", name: "Navette Or Hochelaga-Maisonneuve", dir: ["Est", "Ouest"] },
    { id: "259", name: "Navette Or Mercier-Ouest", dir: ["Est", "Ouest"] },
    { id: "260", name: "Navette Or Anjou", dir: ["Nord", "Sud"] },
    { id: "262", name: "Navette Or Côte-Saint-Luc", dir: ["Sud", "Nord"] },
    { id: "263", name: "Navette Or Bordeaux-Cartierville", dir: ["Ouest", "Est"] },

    { id: "711", name: "Parc-du-Mont-Royal / Oratoire", dir: ["Est", "Ouest"] },
    { id: "720", name: "Omnium Tennis", dir: ["Est", "Ouest"] },
    { id: "730", name: "Des Alouettes", dir: ["Nord", "Sud"] },
    { id: "767", name: "La Ronde / Station Jean-Drapeau", dir: ["Est", "Ouest"] },
    { id: "768", name: "Plage-Jean-Doré", dir: ["Est", "Ouest"] },
    { id: "769", name: "La Ronde / Station Papineau", dir: ["Nord", "Sud"] },
    { id: "777", name: "Jean-Drapeau / Casino / Bonaventure", dir: ["Est", "Ouest"] },
    { id: "804", name: "Belvédère Kondiaronk", dir: ["Est", "Ouest"] },
    { id: "811", name: "Navette Services santé", dir: ["Ouest"] },
    { id: "822", name: "Navette Longue-Pointe", dir: ["Boucle"] },
    { id: "872", name: "Île-des-Soeurs", dir: ["Nord", "Sud"] },
    { id: "968", name: "Trainbus Roxboro / Côte-Vertu", dir: ["Est", "Ouest"] }
  ],

  "Liaisons REM (2026)": [
    { id: "522", name: "REM Bois-Franc / Côte-Vertu", dir: ["Est", "Ouest"] },
    { id: "526", name: "Côte-Vertu / REM Côte-de-Liesse", dir: ["Est", "Ouest"] },
    { id: "527", name: "REM Côte-de-Liesse / REM Bois-Franc", dir: ["Ouest", "Est"] },
    { id: "812", name: "REM Côte-de-Liesse / Côte-Vertu", dir: ["Ouest", "Est"] }
  ]
};
